version: "3.9"

services:
  mlflow:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow
    restart: unless-stopped

  train:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_train
    volumes:
      - ./artifacts:/app/artifacts
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - mlflow
    restart: "no"

  evaluate:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_evaluate
    volumes:
      - ./artifacts:/app/artifacts
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - train
    restart: "no"

  streamlit:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./artifacts:/app/artifacts
      - ./logs:/app/logs
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      - evaluate
    restart: unless-stopped
